
name: REBASE

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you're using

    - name: Install dependencies
      run: npm install 

      # Start PM2 application
    - name: Start PM2 application
      run: pm2 start ecosystem.config.js --env production

    # Graceful reload of the PM2 process
    - name: Reload PM2 application
      run: pm2 reload all

    # Restart Nginx to ensure it's running after PM2
    # - name: Restart nginx service
    #   run: sudo service nginx restart
